version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-v3-{{ checksum "packages/web/package-lock.json" }}
      - run:
          command: cd packages/web && npm ci
          name: Installing NPM packages
      - run:
          command: cd packages/web && npm run build
          name: Build
          environment:
            ANALYZE: 1
      - store_artifacts:
          path: .next/analyze
      - save_cache:
          key: node-deps-v3-{{ checksum "packages/web/package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
            - ./packages/web/.next/cache

workflows:
  main:
    jobs:
      - build
